import type { UserInfo } from "./types";

export async function sendEmailWithPDF(
  email: string,
  pdfBlob: Blob,
  fileName: string,
  userInfo: UserInfo,
): Promise<boolean> {
  try {
    const formData = new FormData();
    formData.append("email", email);
    formData.append("subject", "Your Environmental Test Report");
    formData.append(
      "message",
      `
      Hello ${userInfo.name || "Client"},
      <br/><br/>
      Please find attached your Environmental Test Report.
      <br/><br/>
      Regards,<br/>Toxin Testers Team
    `,
    );
    formData.append("attachment", pdfBlob, fileName);

    // Example API route — replace with your actual backend or n8n webhook URL
    const response = await fetch("https://daku-maha.app.n8n.cloud/webhook/webhook-testing", {
      method: "POST",
      body: formData,
    });

    return response.ok;
  } catch {
    return false;
  }
}

/**
 * Send the PDF to the webhook as a Markdown file attachment.
 * The markdown file will include the provided markdownPrefix and a data-uri link to the PDF.
 */
export async function sendPdfAsMarkdownAttachment(
  webhookUrl: string,
  userEmail: string,
  pdfBlob: Blob,
  fileName: string,
  markdownPrefix = "# Environmental Test Report",
): Promise<boolean> {
  try {
    // convert blob to base64 (chunked)
    const toBase64 = async (blob: Blob) => {
      const buffer = await blob.arrayBuffer();
      const bytes = new Uint8Array(buffer);
      const chunkSize = 0x8000;
      let binary = "";
      for (let i = 0; i < bytes.length; i += chunkSize) {
        const chunk = bytes.subarray(i, i + chunkSize);
        binary += String.fromCharCode.apply(null, Array.from(chunk) as any);
      }
      return btoa(binary);
    };

    const base64 = await toBase64(pdfBlob);

    // Build markdown content that links to the PDF as a data URI
    const safeFileName = fileName.replace(/[^a-z0-9_.-]/gi, "_");
    const mdContent = `${markdownPrefix}\n\n[Download Report: ${safeFileName}](data:application/pdf;base64,${base64})\n\n*Generated by Toxin Testers*`;

    const mdBlob = new Blob([mdContent], { type: "text/markdown" });
    const mdFileName = safeFileName.replace(/\.pdf$/i, ".md");

    const form = new FormData();
    form.append("email", userEmail);
    form.append("subject", `Environmental Test Report - ${safeFileName}`);
    form.append("markdown", mdContent);
    // Attach the markdown file as 'attachment'
    form.append("attachment", mdBlob, mdFileName);

    const res = await fetch(webhookUrl, {
      method: "POST",
      body: form,
    });

    return res.ok;
  } catch (_err) {
    return false;
  }
}
